images:
  tf_operator: atsgen/tf-operator:v0.0.1
  test: psethi/noop:v0.0.1
  imagePullPolicy: "IfNotPresent"

clusterName: k8s

auth:
  tungsten_auth: atsgen

networking:
  ipFabricSubnet: 10.64.0.0/12
  podSubnet: 10.32.0.0/12
  serviceSubnet: 10.96.0.0/12
  # only supported value is enabled or snat
  ipForwarding: snat
  useHostNewtorkService: true
