{{- $envAll := . }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ print .Release.Name "-test" }}
  annotations:
    "helm.sh/hook": test-success
  labels:
{{ tuple $envAll "tungsten-fabric" "tf-operator-test" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  restartPolicy: Never
  containers:
    - name: coredns-test
      image: {{ .Values.images.test }}
      imagePullPolicy: {{ .Values.images.imagePullPolicy }}
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
